title: AV82 STUDIO
email: geral@av82studio.com
description: >- # this means to ignore newlines until "baseurl:"
  AV82 é um estúdio de fotografia e vídeo localizado no centro do Porto. Este é um espaço que não só permite a realização de trabalhos fotográficos como também o aluguer de material, seja ele de fotografia ou video.
url: "av82studio.com" # the base hostname & protocol for your site, e.g. http://example.com


markdown: kramdown # or choose your preferred Markdown converter

# Specify the Markdown file extensions to process
markdown_ext: "md, markdown"

# Configure the Markdown converter options
kramdown:
  input: GFM
  smart_quotes: lsquo, rsquo, ldquo, rdquo
  entity_output: as_char # Convert HTML entities to Unicode characters


# Build settings
permalink: pretty 
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass

collections:
  photo: 
    output: true
  film:
    output: true
  products:
    output: true


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
