---
new_page_extension: html
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: heading
  label: Rental Products
- type: directory
  path: _products
  label: Products
  create: documents
  match: "**/*"
  new_doc_ext: html
  templates:
  - gear-onset
  - gear-ge
  - gear-image
  - gear-light
  - gear-audio
  - product
- type: document
  path: booking2.html
  label: Gear Categories
- type: heading
  label: Projects
- type: directory
  path: _film
  label: Film
  create: all
  match: "**/*"
  new_doc_ext: html
  templates:
  - film
- type: document
  path: film.html
  label: Film Project Order
- type: directory
  path: _photo
  label: Photo
  create: all
  match: "**/*"
  new_doc_ext: html
  templates:
  - photo
- type: document
  path: photo.html
  label: Photo Project Order
- type: heading
  label: Pages
- type: document
  path: index.html
  label: 'Home '
  match: "**/*"
- type: heading
  label: Recurring Elements
- type: document
  path: _layouts/black.html
  label: Menu
- type: document
  path: _data/about.yml
  label: About
upload_dir: assets/img
public_path: "/assets/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
