backend:
  name: git-gateway
  branch: master 


media_folder: "assets/img"

publish_mode: editorial_workflow


collections:
  - label: Páginas
    name: pages
    files: 
      - label: 'Rental'
        name: rental
        file: 'rental.html'
        editor:
          preview: false
        fields:
          - name: layout
            label: layout
            widget: hidden
          - {name: intro_pt , label: Intro PT , widget: markdown, modes: [rich_text] }
          - {name: intro_eng , label: Intro ENG , widget: markdown, modes: [rich_text] }
          - {name: studio_pt , label: Estúdio PT , widget: markdown, modes: [rich_text] }
          - {name: studio_eng , label: Studio ENG , widget: markdown, modes: [rich_text] }
          - {name: studio_img , label: Studio Img , widget: image }
          - {name: material_pt , label: Material PT , widget: markdown, modes: [rich_text] }
          - {name: material_eng , label: Material ENG , widget: markdown, modes: [rich_text] }
          - {name: material_img , label: Material Img , widget: image }
          - {name: crew_pt , label: Equipa PT , widget: markdown, modes: [rich_text] }
          - {name: crew_eng , label: Crew ENG , widget: markdown, modes: [rich_text] }
          - {name: crew_img , label: Crew Img , widget: image }
          - {name: transport_pt , label: Transporte PT , widget: markdown, modes: [rich_text] }
          - {name: transport_eng , label: Mobility ENG , widget: markdown, modes: [rich_text] }
          - {name: mobility_img , label: Mobility Img , widget: image }
      - label: Team
        name: team
        file: 'team.html'
        editor:
          preview: false
        fields:
          - {name: layout, label: layout, widget: hidden}
          - name: team_members
            label: Team Members
            widget: list
            fields:
              - {name: name, label: Nome, widget: string}
              - {name: roles_eng, label: Roles, hint: ENG, widget: list}
              - {name: roles_pt, label: Funções, hint: PT, widget: list}
              - {name: retrato, label: Retrato, widget: image}
      - file: index.html
        label: Home
        name: home
        editor:
          preview: false
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: index-page
          - label: Showreel
            name: showreel
            required: true
            widget: string
            hint: ""
            default: ""
      - file: photo.html
        label: Photo Order
        name: photo_order
        editor:
          preview: false
        fields:
          - {name: project_order, label: Project Order, widget: relation, collection: "photo", search_fields: ['title'], value_field: '_photo/{{filename}}.{{extension}}', display_fields: ['title'], required: false, multiple: true}
      - file: film.html
        label: Film Order
        name: film_order
        editor:
          preview: false
        fields:
          - {name: project_order, label: Project Order, widget: relation, collection: "film", search_fields: ['title'], value_field: '_film/{{filename}}.{{extension}}', display_fields: ['title'], required: false, multiple: true}
  - name: film
    label: Film
    extension: html
    folder: '_film'
    create: true
    slug: "{{slug}}"
    editor:
          preview: false
    fields:
      - label: layout
        name: layout
        widget: hidden
        default: film-project
        required: true
        hint: ""
      - label: Title
        name: title
        widget: string
        required: true
        hint: ""
        default: ""
      - label: Category
        name: category
        required: false
        widget: select
        hint: ""
        default: ""
        options:
          - films
          - commercial
          - fashion
          - music
        multiple: false
      - label: Synopsis
        name: synopsis
        widget: markdown
        modes: [rich_text]
        required: false
        hint: ""
        default: ""
        buttons:
          - bold
          - italic
          - link
      - label: Sinopse
        name: sinopse
        widget: markdown
        modes: [rich_text]
        required: false
        hint: ""
        default: ""
        buttons:
          - bold
          - italic
          - link
      - label: Credits
        name: credits
        required: false
        widget: markdown
        modes: [rich_text]
        hint: ""
        default: ""
        buttons:
          - bold
          - italic
          - link
      - label: Créditos
        name: creditos
        required: false
        widget: markdown
        modes: [rich_text]
        hint: ""
        default: ""
        buttons:
          - bold
          - italic
          - link
      - label: Video Embed
        name: video_embed
        required: false
        widget: markdown
        modes: [rich_text]
        hint: "Selecionar Tamanho: Responsive, Reproduzir     este vídeo
          automaticamente e Ativar repetição deste vídeo.     Tudo o resto
          desligado."
        default: ""
        buttons:
          - code
      - label: Stills
        name: stills
        required: false
        widget: image
        media_library:
            config:
              multiple: true
      - label: Video Thumbnail
        name: video_thumbnail
        required: true
        widget: file
        hint: O video que aparece quando se faz hover sobre o still. Em mp4 e o mais
          pequeno possivel.
        allow_multiple: false
      - label: Still Thumbnail
        name: still_thumbnail
        required: true
        widget: image
        allow_multiple: false
      - label: Large
        name: large
        required: false
        widget: boolean
        hint: Ligar se quiserem fazer highlight deste projeto.
        default: ""
    identifier_field: title
  - name: photo
    label: Photo
    extension: html
    folder: '_photo'
    create: true
    slug: "{{slug}}"
    editor:
          preview: false
    fields:
      - label: layout
        name: layout
        widget: hidden
        default: photo-project
        required: true
      - label: Title
        name: title
        widget: string
        required: true
        hint: ""
        default: ""
      - label: Category
        name: category
        required: false
        widget: select
        options:
          - fashion
          - commercial
          - portraita
        multiple: false
      - label: Description
        name: description
        widget: markdown
        modes: [rich_text]
        required: false
        buttons:
          - bold
          - italic
          - link
      - label: Descrição
        name: description_pt
        widget: markdown
        modes: [rich_text]
        buttons:
          - bold
          - italic
          - link
      - label: Credits
        name: credits
        required: false
        widget: markdown
        modes: [rich_text]
        buttons:
          - bold
          - italic
          - link
      - label: Créditos
        name: credits_pt
        required: false
        widget: markdown
        modes: [rich_text]
        buttons:
          - bold
          - italic
          - link
      - label: Stills
        name: stills
        required: false
        widget: image
        media_library:
            config:
              multiple: true
      - label: Thumbnail
        name: thumbnail
        required: true
        widget: image
        allow_multiple: false
    identifier_field: title
  - label: "Gear"
    name: "gear"
    folder: '_products/Gear'
    create: true
    extension: html
    slug: '{{slug}}'
    editor:
          preview: false
    fields:
      - {label: 'Name', name: 'title', widget: 'string'}
      - {label: 'Nome', name: 'title_pt', wiget: 'string', hint: em pt. se for igual à versão inglesa, deixar vazio., required: false}
      - {label: 'Description', name: description, required: false, widget: markdown, modes: [rich_text] }
      - {label: Descrição, name: description_pt, required: false, widget: markdown, modes: [rich_text], hint: em pt. se for igual à versão inglesa, deixar vazio., required: false}
      - {name: category, label: Category, widget: 'select', options: ['Light','Image', 'Audio', 'G&E', 'On Set'] }
      - {name: subcategory, label: Sub-Category, widget: 'select', options: ['Cameras', 'Lenses', 'Monitors', 'Wireless', 'Live Streaming', 'Drone', 'Others', 'Media', 'Power', 'Filters', 'Audio', 'Continuous Light', 'Flash', 'Light Modifiers', 'Frames', 'Reflectors', 'Stabilizers/Gimbals', 'Tripods/Fluid Heads', 'Dollies/Sliders', 'Grip', 'Power', 'Effects', 'Magliner', 'COM' ] }
      - {name: subcategoria, label: Sub-Categoria, widget: 'select', options: ['Câmaras', 'Objetivas', 'Monitores', 'Wireless', 'Live Streaming', 'Outros', 'Media', 'Power', 'Filtros','Áudio', 'Luz Contínua', 'Flash', 'Modificadores de Luz', 'Frames', 'Refletores', 'Stabilizers/Gimbals', 'Tripés/Cabeças Fluídas', 'Dollies/Sliders', 'Grip', 'Power', 'Efeitos', 'Magliner', 'COM'] }
      - name: images
        label: Images 
        widget: image
        media_library:
            config:
              multiple: true
      - {name: price_day, widget: number, label: 'Price/day', required: false, default: 0}
      - {name: available_quantity, widget: number, label: 'Available Quantity', default: 1, required: false, hint: Limite de items para adicionar ao carrinho}
      - {name: recommended, label: Recommended, required: false, widget: relation, collection: "gear", search_fields: ['title'], value_field: '_products/Gear/{{filename}}.{{extension}}', display_fields: ['title'], required: false, multiple: true}
      - {name: type, label: Type, widget: hidden, default: Gear}
      - {name: layout, label: layout, widget: hidden, default: white}
  - label: "Studio"
    name: "studio"
    folder: '_products/Studio'
    create: true
    extension: html
    slug: '{{slug}}'
    editor:
          preview: false
    fields:
      - {label: 'Name', name: 'title', widget: 'string'}
      - {label: 'Nome', name: 'title_pt', wiget: 'string', hint: em pt. se for igual à versão inglesa, deixar vazio., required: false}
      - {label: 'Description', required: false, name: description, widget: markdown, modes: [rich_text] }
      - {label: Descrição, required: false, name: description_pt, widget: markdown, modes: [rich_text], hint: em pt. se for igual à versão inglesa, deixar vazio., required: false}
      - {name: type, label: Type, widget: 'hidden', default: 'Studio' }
      - name: images
        label: Images 
        widget: image
        media_library:
            config:
              multiple: true
      - {name: price_day, widget: number, label: 'Price/day', required: true, default: 0}
      - {name: recommended, label: Recommended,required: false, widget: relation, collection: "_products/Studio", search_fields: ['title'], value_field: 'title'}
      - {name: layout, label: layout, widget: hidden, default: white}
  - label: "Mobility"
    name: "mobility"
    folder: '_products/Mobility'
    create: true
    extension: html
    slug: '{{slug}}'
    editor:
          preview: false
    fields:
      - {label: 'Name', name: 'title', widget: 'string'}
      - {label: 'Nome', name: 'title_pt', wiget: 'string', hint: em pt. se for igual à versão inglesa, deixar vazio., required: false}
      - {label: 'Description',required: false, name: description, widget: markdown, modes: [rich_text] }
      - {label: Descrição,required: false, name: description_pt, widget: markdown, modes: [rich_text], hint: em pt. se for igual à versão inglesa, deixar vazio.}
      - {name: type, label: Type, widget: 'hidden', default: 'Mobility' }
      - name: images
        label: Images 
        widget: image
        media_library:
            config:
              multiple: true
      - {name: price_day, widget: number, label: 'Price/day', required: false, default: 0}
      - {name: layout, label: layout, widget: hidden, default: white}
  - label: "Crew"
    name: "crew"
    folder: '_products/Crew'
    create: true
    extension: html
    slug: '{{slug}}'
    editor:
          preview: false
    fields:
      - {label: 'Name', name: 'title', widget: 'string'}
      - {label: 'Nome', name: 'title_pt', wiget: 'string', hint: em pt. se for igual à versão inglesa, deixar vazio., required: false}
      - {label: 'Description', name: description,required: false, widget: markdown, modes: [rich_text] }
      - {label: Descrição, name: description_pt,required: false, widget: markdown, modes: [rich_text], hint: em pt. se for igual à versão inglesa, deixar vazio., required: false}
      - {name: type, label: Type, widget: 'hidden', default: 'Crew' }
      - name: images
        label: Images 
        widget: image
        media_library:
            config:
              multiple: true
      - {name: price_day, widget: number, label: 'Price/day', required: false, default: 0}
      - {name: layout, label: layout, widget: hidden, default: white}
