---
label: Product (Studio/Mobility/Crew)
hide_body: true
fields:
- name: title
  type: text
  config:
    required: false
  label: Name
- name: title_pt
  type: text
  config:
    required: false
  label: Nome
  description: em pt. se for igual à versão inglesa, deixar vazio.
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html-blocks
  label: Description
- name: description_pt
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html-blocks
  label: Descrição
  description: em pt. se for igual à versão inglesa, deixar vazio.
- name: type
  type: select
  default: []
  config:
    required: false
    options:
    - Studio
    - Crew
    - Mobility
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Type
- name: images
  type: image_gallery
  config: {}
  label: Images
- name: price_day
  type: number
  label: Price/day
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: recommended
  type: list
  config:
    use_select: true
    min: 
    max: 
    source:
      type: pages
      section: products
  label: Recommended
- name: selection
  type: tag_list
  default: []
  label: Selection
  description: Se o produto tem várias opções, adicionar aqui.
- name: layout
  type: text
  config:
    required: false
  label: layout
  default: white
  hidden: true
pages:
- _products/Crew/1st-ac.html
- _products/Crew/art-director.html
- _products/Crew/camera-operator.html
- _products/Crew/director-assistant.html
- _products/Crew/director-of-photography.html
- _products/Crew/director.html
- _products/Crew/drone-operator.html
- _products/Crew/gaffer.html
- _products/Crew/gimbal-operator.html
- _products/Crew/hair-make-up.html
- _products/Crew/photographer.html
- _products/Crew/photography-digital-assistant.html
- _products/Crew/producer.html
- _products/Crew/production-assistant.html
- _products/Crew/runner.html
- _products/Crew/stylist.html
- _products/Studio/coffee-and-water-pack-dia-inteiro.html
- _products/Studio/coffee-and-water-pack-full-day.html
- _products/Studio/digital-station.html
- _products/Studio/e-commerce-pack.html
- _products/Studio/studio-half-day-5h.html
