---
label: Product (Gear)
hide_body: true
fields:
- name: layout
  type: text
  config:
    required: false
  label: layout
  default: white
  hidden: true
- name: title
  type: text
  config:
    required: false
  label: Name
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html-blocks
  label: Description
- name: type
  type: select
  default: Photography
  config:
    required: false
    options:
    - Film
    - Studio
    - Mobility
    - Gear
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Type
- name: category
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Category
- name: subcategory
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: documents
      section: product-categories
      file: booking2.html
      path: photo_categories
  label: Sub-Category
- name: images
  type: image_gallery
  config: {}
  label: Images
- name: price_day
  type: number
  label: Price/day
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: recommended
  type: list
  config:
    use_select: true
    min: 
    max: 
    source:
      type: pages
      section: products
  label: Recommended
pages:
- _products/Photography/canon-17-40mm-l-usm-f-4.html
- _products/Photography/canon-5d-mk4-1.html
