---
label: Product
hide_body: true
fields:
- name: layout
  type: text
  config:
    required: false
  label: layout
  default: project
  hidden: true
- name: title
  type: text
  config:
    required: false
  label: Name
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html-blocks
  label: Description
- name: type
  type: select
  default: []
  config:
    required: false
    options:
    - Photography
    - Film
    - Studio
    - Crew
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Type
- name: images
  type: image_gallery
  config: {}
  label: Images
- name: price_day
  type: number
  label: Price/day
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: category
  type: tag_list
  default: []
  label: Category
- name: recommended
  type: list
  config:
    use_select: true
    min: 
    max: 
    source:
      type: pages
      section: products
  label: Recommended
pages:
- _products/black-magic-pocket-cinema-camera-6k-pro.html
- _products/canon-5d-mk4.html
- _products/full-day-10h.html
