---
label: Product Categories
hide_body: true
fields:
- type: text
  name: layout
  label: layout
  hidden: true
- name: imagem_pt
  type: tag_list
  default: []
  label: IMAGEM
  description: Versão PT
- name: imagem_eng
  type: tag_list
  default: []
  label: IMAGE
  description: Versão ENG
- name: audio_pt
  type: tag_list
  default: []
  label: ÁUDIO
  description: Versão PT
- name: audio_eng
  type: tag_list
  default: []
  label: AUDIO
  description: Versão ENG
- name: luz_pt
  type: tag_list
  default: []
  label: LUZ
  description: Versão PT
- name: light_eng
  type: tag_list
  default: []
  label: LIGHT
  description: Versão ENG
- name: ge_pt
  type: tag_list
  default: []
  label: G&E PT
  description: Versao PT
- name: ge_eng
  type: tag_list
  default: []
  label: G&E ENG
  description: Versão ENG
pages:
- booking2.html
